### ISSUE TITLE
Webstorm highlight

### ISSUE THREAD

**Issue by romanlex** [coreprocess/babel-plugin-js-logger#3]
Hello. How I can add hightlight library in Webstorm correctly?
If I use global Logger - when all work prefectly. if I use logger, when I has IDEA notificication what logger not imported.

**Comment by coreprocess** [comment]
Webstorm simply does not know about the injected logger variable. Maybe Webstorm supports suppression of specific errors?

If not, could you try the following approaches?

1) Could you try to add the following workaround at the top of the main entry point of your project?
```js
// in nodejs
global.logger = typeof logger != 'undefined' ? logger : console;
// in browser
window.logger = typeof logger != 'undefined' ? logger : console;
```

2) If it does not work, could you try to place the following at the top of every javascript file?
```js
var logger = typeof logger != 'undefined' ? logger : console;
```
